project:
  type: website

website:
  title: "jgoliv"
  page-navigation: true
  open-graph: true

  navbar: 
    style: "floating"
    tools:
      - icon: github
        href: https://github.com/jgoliv
      - icon: linkedin
        href: https://linkedin.com/in/jgoliv
    left: 
      - index.qmd
      - projects.qmd
      - articles.qmd

  sidebar:
    - id: projects
      style: "floating"
      logo: www/images/logo.svg
      logo-href: /index.qmd
      contents: 
        - projects.qmd
        - section: "Machine learning cases"
          contents: 
            - projects/ml_cases/titanic_binary_classification/project.qmd
        - section: "R & Shiny"
          contents: 
            - projects/r_shiny/japan_biodiversity_dashboard/project.qmd
    - id: articles
      contents: 
        - articles.qmd
        - articles/price_tracking_with_py_selenium/article.qmd
        - articles/visualizing_proportions_with_echarts4r/article.qmd

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    smooth-scroll: true
    toc: true
    theme: [cosmo, www/css/theme.scss]
    grid:
      sidebar-width: 300px
      body-width: 900px

editor: visual
