project:
  type: website
  resources:
    - www/fonts/*
  
website:
  page-navigation: true
  open-graph: true
  repo-url: https://github.com/jgoliv/jgoliv.github.io
  repo-actions: [source]

  navbar:
    style: "floating"
    title: false
    tools:
      - icon: github
        href: https://github.com/jgoliv
      - icon: linkedin
        href: https://linkedin.com/in/jgoliv
    left:
      - text: "About"
        href: index.qmd
      - text: "Portfolio"
        href: portfolio.qmd

  sidebar:
    - id: projects
      style: "floating"
      logo: www/images/logo.svg
      logo-href: index.qmd
      contents: 
        - portfolio.qmd
        - text: "---"
        - section: "R & Shiny"
          contents:
            - portfolio/r-shiny/japan-biodiversity-dashboard/article.qmd
        - section: "Data Viz"
          contents:
            - section: "Math Series"
              contents:
                - portfolio/data-viz/math-series/kuratowski-closure-complement/article.qmd

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    smooth-scroll: true
    toc: true
    theme:
      - cosmo
      - www/css/theme.scss
    grid:
      sidebar-width: 300px
      body-width: 900px
