project:
  type: website
  resources:
    - www/fonts/*
    - www/icons/*

execute:
  freeze: true

website:
  search: false
  page-navigation: true
  open-graph: true
  repo-url: https://github.com/jgoliv/jgoliv.github.io
  repo-actions: [source]

  navbar:
    title: false
    left:
      - icon: house
        text: " "
        href: index.qmd
        aria-label: Home
      - text: "About"
        href: index.qmd#about-me

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    smooth-scroll: true
    toc: true
    theme:
      dark: [www/themes/theme-light.scss, www/themes/theme-dark.scss]
      light: www/themes/theme-light.scss
    highlight-style: www/themes/custom-highlight.theme
    fontsize: 16px
    grid:
      body-width: 900px
