project:
  type: website

website:
  page-navigation: true
  open-graph: true

  sidebar:
    style: "floating"
    search: true
    title: "João Gabriel Oliveira"
    logo: www/images/logo.svg
    logo-alt: "João Gabriel Oliveira"
    logo-href: /index.qmd

    tools:
      - icon: github
        href: https://github.com/jgoliv
      - icon: linkedin
        href: https://linkedin.com/in/joão-gabriel-oliveira-jesus

    contents:
      - index.qmd
      - section: "Projects"
        contents:
          - section: "Machine learning cases"
            contents: 
              - projects/ml_cases/titanic_binary_classification/project.qmd
          - section: "R & Shiny"
            contents: 
              - projects/r_shiny/japan_biodiversity_dashboard/project.qmd
      - section: "Articles"
        contents: 
          - section: "Automation"
            contents: 
              - articles/price_tracking_with_py_selenium/article.qmd
          - section: "Data visualization"
            contents:
              - articles/visualizing_proportions_with_echarts4r/article.qmd
              - articles/working_with_spatial_data_in_R/article.qmd"

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    smooth-scroll: true
    theme: [cosmo, www/css/theme.scss]
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px

editor: visual