project:
  type: website
  resources:
    - www/fonts/*
    - www/icons/*

execute:
  freeze: true

website:
  search: false
  page-navigation: true
  open-graph: true
  repo-url: https://github.com/jgoliv/jgoliv.github.io
  repo-actions: [source]

  navbar:
    title: false
    left:
      - icon: house
        text: " "
        href: index.qmd
        aria-label: Home
      - text: "About"
        href: index.qmd#about-me

  page-footer:
    border: false
    left: Website made with <a href="https://quarto.org"><span class="footer-quarto-icon" aria-hidden="true"></span>Quarto</a> v.{{< version >}}

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    smooth-scroll: true
    toc: true
    theme: www/css/theme.scss
    highlight-style: monokai
    fontsize: 16px
    grid:
      body-width: 900px
